<Workspace Version="0.7.5.3566" X="30" Y="377.41875" zoom="1.0015625" Description="Returns the underlying Revit element of a given face" Category="Clockwork.Revit.Selection.ByFace" Name="Element.FromDynamoSurface" ID="0b4bb7ab-9433-4f3c-8abe-d26de134cc8c">
  <Elements>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="68b99055-51d7-439f-a477-59bcd538a6d4" nickname="ReturnListOrSingleValue" x="889" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="44ac4888-4aa4-49a9-9344-23b729c11df9" />
      <Name value="ReturnListOrSingleValue" />
      <Description value="If the item in input #1 is not a list, only the first item of the list in input #2 will be returned." />
      <Inputs>
        <Input value="item #1 (unknown)" />
        <Input value="item #2 (list)" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="3be69790-bfc1-4373-a6d1-1f910b467849" nickname="Turn Into List" x="244" y="26" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="Turn Into List" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="item" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="eda74bfc-0b6e-4bc1-92cc-e97715efcc88" nickname="Input" x="0" y="13" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Dynamo surface(s)" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="d5e9bf9e-2e10-42a3-b3e6-45d8495ab233" nickname="Output" x="1181" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Element(s)" />
    </Dynamo.Nodes.Output>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="fa360464-4fbd-45c1-bf31-e3292ff8a9c7" nickname="Python Script" x="449" y="26" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
faces = UnwrapElement(IN[0])
elementlist = list()
for face in faces:
	try:
		ref = face.Tags.LookupTag("RevitFaceReference")
		elem = doc.GetElement(ref)
		elementlist.append(elem)
	except:
		elementlist.append(list())
OUT = elementlist</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="733caf1e-1f76-45ff-ab39-9cc6638e0441" nickname="List.UniqueItems" x="673" y="26" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="DSCoreNodes.dll" function="DSCore.List.UniqueItems@var[]..[]" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="68b99055-51d7-439f-a477-59bcd538a6d4" start_index="0" end="d5e9bf9e-2e10-42a3-b3e6-45d8495ab233" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="3be69790-bfc1-4373-a6d1-1f910b467849" start_index="0" end="fa360464-4fbd-45c1-bf31-e3292ff8a9c7" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="eda74bfc-0b6e-4bc1-92cc-e97715efcc88" start_index="0" end="3be69790-bfc1-4373-a6d1-1f910b467849" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="eda74bfc-0b6e-4bc1-92cc-e97715efcc88" start_index="0" end="68b99055-51d7-439f-a477-59bcd538a6d4" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="fa360464-4fbd-45c1-bf31-e3292ff8a9c7" start_index="0" end="733caf1e-1f76-45ff-ab39-9cc6638e0441" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="733caf1e-1f76-45ff-ab39-9cc6638e0441" start_index="0" end="68b99055-51d7-439f-a477-59bcd538a6d4" end_index="1" portType="0" />
  </Connectors>
  <Notes />
</Workspace>