{
  "Uuid": "576880d2-5f2c-4e34-9183-359361aaa077",
  "IsCustomNode": true,
  "Category": "Clockwork.Geometry.Curves.Create",
  "Description": "Creates a *closed* loop of curves based on a given list of points",
  "Name": "Curve.ClosedLoopThroughPoints",
  "ElementResolver": {
    "ResolutionMap": {
      "PolyCurve": {
        "Key": "Autodesk.DesignScript.Geometry.PolyCurve",
        "Value": "ProtoGeometry.dll"
      },
      "Autodesk.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [
    {
      "Id": "d54deaabe6eb4ef1858b8790c179262a",
      "Name": "Boolean",
      "Type": "boolean",
      "Value": "true",
      "Description": "Selection between a true and false."
    }
  ],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "points",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": 1,
        "DefaultValue": null
      },
      "Id": "ce17390f15224ac4b6e69152d83e7a97",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "1c99ae0408c34b3c95e355ff2d899934",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Curves",
      "Id": "0199b100662e48cbab5cf6a4ed55d5cf",
      "Inputs": [
        {
          "Id": "1f649877d4644fa2851718ae6d1e4c24",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.PolyCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[],bool",
      "Id": "5392ff8469ed4330a05d385131ee9cd8",
      "Inputs": [
        {
          "Id": "f69e1261584a41589ed54a4a5de3c96a",
          "Name": "points",
          "Description": "Points to make polycurve\n\nPoint[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bb84e9fe572a4c3ab8dc0100edaf2a3d",
          "Name": "connectLastToFirst",
          "Description": "make close or open polycurve\n\nbool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "60e679fc28e048348440f4ca3e040d46",
          "Name": "PolyCurve",
          "Description": "PolyCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Make PolyCurve by connecting points. Set the 'connectLastToFirst' input to true to close the PolyCurve.\n\nPolyCurve.ByPoints (points: Point[], connectLastToFirst: bool = false): PolyCurve"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.BoolSelector, CoreNodeModels",
      "NodeType": "BooleanInputNode",
      "InputValue": true,
      "Id": "d54deaabe6eb4ef1858b8790c179262a",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "dbd163cb68f34fc3ac5fc8e1afb023e7",
          "Name": "",
          "Description": "Boolean",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Selection between a true and false."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.PolyCurve.Curves",
      "Id": "638b4830596f4c5bad1153164281e348",
      "Inputs": [
        {
          "Id": "78120ff736d5421889761decac484db3",
          "Name": "polyCurve",
          "Description": "Autodesk.DesignScript.Geometry.PolyCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "8b422b8a556f411780bc1d251d8687e0",
          "Name": "Curve[]",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Returns curves of the polycurve\n\nPolyCurve.Curves ( ): Curve[]"
    }
  ],
  "Connectors": [
    {
      "Start": "1c99ae0408c34b3c95e355ff2d899934",
      "End": "f69e1261584a41589ed54a4a5de3c96a",
      "Id": "18176f8f56cd4056aa8c24f90190a383"
    },
    {
      "Start": "60e679fc28e048348440f4ca3e040d46",
      "End": "78120ff736d5421889761decac484db3",
      "Id": "e0381a7c5b344410bcf6d290cf5bd187"
    },
    {
      "Start": "dbd163cb68f34fc3ac5fc8e1afb023e7",
      "End": "bb84e9fe572a4c3ab8dc0100edaf2a3d",
      "Id": "940b5133f32e4f82be7f4e9da2426b38"
    },
    {
      "Start": "8b422b8a556f411780bc1d251d8687e0",
      "End": "1f649877d4644fa2851718ae6d1e4c24",
      "Id": "067d534f841246c69fc0a66116237528"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.0.4654",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "Id": "ce17390f15224ac4b6e69152d83e7a97",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -101.791682947826,
        "Y": 48.5942986496884
      },
      {
        "Id": "0199b100662e48cbab5cf6a4ed55d5cf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 952.208317052174,
        "Y": 77.5942986496884
      },
      {
        "Id": "5392ff8469ed4330a05d385131ee9cd8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "PolyCurve.ByPoints",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 234.208317052174,
        "Y": 77.5942986496884
      },
      {
        "Id": "d54deaabe6eb4ef1858b8790c179262a",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Name": "Boolean",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -101.791682947826,
        "Y": 132.594298649688
      },
      {
        "Id": "638b4830596f4c5bad1153164281e348",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "PolyCurve.Curves",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 628.208317052174,
        "Y": 77.5942986496884
      }
    ],
    "Annotations": [],
    "X": 87.7872012981285,
    "Y": 440.757094766027,
    "Zoom": 1.17691128698145
  }
}