{
  "Uuid": "61bda511-27e0-4a68-8668-c3ed1c24b62e",
  "IsCustomNode": true,
  "Category": "Clockwork.Revit.Elements.Actions",
  "Description": "Creates a number of equally spaced vertical intersects for a divided surface based on the path between between two points. You may need to switch start point and end point.",
  "Name": "DividedSurface.VerticalIntersectsByEndpoints",
  "ElementResolver": {
    "ResolutionMap": {
      "Line": {
        "Key": "Autodesk.DesignScript.Geometry.Line",
        "Value": "ProtoGeometry.dll"
      },
      "List": {
        "Key": "DSCore.List",
        "Value": "DSCoreNodes.dll"
      },
      "Vector": {
        "Key": "Autodesk.DesignScript.Geometry.Vector",
        "Value": "ProtoGeometry.dll"
      },
      "ReferencePlane": {
        "Key": "Revit.Elements.ReferencePlane",
        "Value": "RevitNodes.dll"
      },
      "Autodesk.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "Autodesk.DesignScript.Geometry.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "DividedSurface": {
        "Key": "Revit.Elements.DividedSurface",
        "Value": "RevitNodes.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "dividedSurface",
        "TypeName": "Revit.Elements.DividedSurface",
        "TypeRank": 0,
        "DefaultValue": null
      },
      "Id": "de4ee521d19f404690e2749c4add666e",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "da5f88b84fb7484aa2b9c3350bd84dec",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "startPoint",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": 0,
        "DefaultValue": null
      },
      "Id": "1b41fe9ccefc4707a8e4dcdb3d8d226c",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "994ce356fd584a00a78e81740d8b4b20",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "endPoint",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": 0,
        "DefaultValue": null
      },
      "Id": "77724451d13545079ba7c5d636637a96",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "a08059741c894714be0e04cc155bf195",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "subdivisions",
        "TypeName": "int",
        "TypeRank": 0,
        "DefaultValue": null
      },
      "Id": "953cdc3aa06b4f71a5d930a462134257",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "796a7561485c4491a6bc66038209bf9d",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "dividedSurface",
      "Id": "02de61aab9a14c1dbe46e10e9bc97000",
      "Inputs": [
        {
          "Id": "8f743ce6223f4be3b4fdf76e12de4199",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "intersects",
      "Id": "1a5794e0884d48cdba01d524fd46214d",
      "Inputs": [
        {
          "Id": "b4a5b036aeee4efaa58b608ecf633b6b",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "e29fe7ec-cf80-41fd-a1a1-d55b01e15697",
      "FunctionType": "Graph",
      "NodeType": "FunctionNode",
      "Id": "0108fe09264c46a2aca8f4d5d82e2366",
      "Inputs": [
        {
          "Id": "e425a32431f549b48e470bbae00a58b5",
          "Name": "dividedSurface",
          "Description": "DividedSurface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a05476966f5947bdb2db92cf99e4d66e",
          "Name": "element",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b4b59b557ffa4b75998eb7e76d75abf6",
          "Name": "dividedSurface",
          "Description": "return value",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Adds an intersect to a divided surface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Subtract@Autodesk.DesignScript.Geometry.Vector",
      "Id": "ad17e8bd13204dbaad00a6bac5352f99",
      "Inputs": [
        {
          "Id": "2e12008398d94c4da2e2da21b2d9b053",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "43389496d54f4a36af60849d0073d09e",
          "Name": "vectorToSubtract",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "88efafa634af4dac9e63d92168a42f9e",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Subtract a vector from a point. The same as Translate(-Vector).\n\nPoint.Subtract (vectorToSubtract: Vector): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double",
      "Id": "efedc59ecafc42d48ac059826ab61510",
      "Inputs": [
        {
          "Id": "2fed2d491ad84690bc43fcf01f87cff3",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1cf65e23a1384ba7ba2c93d7c924e495",
          "Name": "param",
          "Description": "The parameter at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b9b09d71bfdf44c8894134eb7185c451",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get a Point on the Curve at a specified parameter between StartParameter() and EndParameter()\n\nCurve.PointAtParameter (param: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.ReferencePlane.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "a5b4099b6e72473b8b6dec4ae688379d",
      "Inputs": [
        {
          "Id": "c1adcc4fc5cb4efda1aa6f0feb30cf07",
          "Name": "start",
          "Description": "The location where the bubble will be located\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6ee4a10f2a7f4f7bb732de96538f37db",
          "Name": "end",
          "Description": "The other end\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f14aac46ba7a47b5abc4bca97f815f8a",
          "Name": "ReferencePlane",
          "Description": "ReferencePlane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Refernece plane from two end points in the Active view. The cut vector is the Z Axis.\n\nReferencePlane.ByStartPointEndPoint (start: Point, end: Point): ReferencePlane"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "43df6cfe-4f8f-42e9-8996-43441bebd19d",
      "FunctionType": "Graph",
      "NodeType": "FunctionNode",
      "Id": "a6a7a211e68e4d378eafc78cc82e44d4",
      "Inputs": [
        {
          "Id": "79419061dbee465abbcbab87091f40c3",
          "Name": "list",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d1c009bc73cd4333a2273aff52ed7690",
          "Name": "list",
          "Description": "Output #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Drops the last item from a given list."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "3a33a6aa6205440d9cd349ec9dfedc72",
      "Inputs": [
        {
          "Id": "c172d2af8f534a1ea57ce187f0d21678",
          "Name": "startPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e65c36a1fc044b22a1958c3154d423c0",
          "Name": "endPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4ccd9510d178430a91f188bd478e7204",
          "Name": "Line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DSCore.List.RestOfItems@var[]..[]",
      "Id": "6c8eac660c2a4f7c868ea725cf4c6213",
      "Inputs": [
        {
          "Id": "cba0d3a62e29459b8b247e6ec3c955ac",
          "Name": "list",
          "Description": "List to get the rest of.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2431103755aa4cb190d4fb5c8c8369e4",
          "Name": "rest",
          "Description": "Rest of the list.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Removes the first item from the given list.\n\nList.RestOfItems (list: var[]..[]): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "l / 10;",
      "Id": "27f3d287d90a4e1e890646e6304f8703",
      "Inputs": [
        {
          "Id": "fb0311bf0bd14e979254ba8cafce2122",
          "Name": "l",
          "Description": "l",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "da116087475a4d2a85411987a409c4de",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Add@Autodesk.DesignScript.Geometry.Vector",
      "Id": "f5ff068bed22459896c6b73915ccea61",
      "Inputs": [
        {
          "Id": "9499db4003b24bc1bc43e91feb33916a",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bb1d810873b04fc2b092a61dca337419",
          "Name": "vectorToAdd",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6cfbb1a0796f41828e5dfa9da095764e",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Add a vector to a point. The same as Translate(Vector).\n\nPoint.Add (vectorToAdd: Vector): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.Length",
      "Id": "d391df1c98514715a1358a87db5dfc47",
      "Inputs": [
        {
          "Id": "2e351439cb134763a35b3e36bab70cf8",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "811c24f285484a9cbcaca83ae83df8c8",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The total arc length of the curve\n\nCurve.Length: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double",
      "Id": "a24282a204f246a99fcbd24ba49b34c7",
      "Inputs": [
        {
          "Id": "e32e2a662c0b4cd0a4032fdb4df33fd7",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4fbfc89f75134c90b1a74c0a7b2024d3",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "5cb148dee9164042b5a78210ceb9838c",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point in the XY plane given two 2 cartesian coordinates. The Z component is 0.\n\nPoint.ByCoordinates (x: double = 0, y: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double",
      "Id": "f4d9b10ae9da44f0b561e4e37ea32894",
      "Inputs": [
        {
          "Id": "4a649f14fcfc4adb8dd89202fe335f3f",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "901c9cdcfb1c47979c75e7812b35b4b6",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4510204efec54f32a59deaf655de38b5",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point in the XY plane given two 2 cartesian coordinates. The Z component is 0.\n\nPoint.ByCoordinates (x: double = 0, y: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "seq = 0..1..#(subdiv+1);",
      "Id": "8c8cf82eb2a545b59142f79bc5d0f9cf",
      "Inputs": [
        {
          "Id": "81cc2b89eaa34c02958697eee31f5f70",
          "Name": "subdiv",
          "Description": "subdiv",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2a31fa7c13a24667997be67ac2e6e731",
          "Name": "",
          "Description": "seq",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.Scale@double",
      "Id": "2a8db5d0e91f47b09e8fe95ca9d70444",
      "Inputs": [
        {
          "Id": "e0b2d3645bb444a992aa15ead74e88a3",
          "Name": "vector",
          "Description": "Autodesk.DesignScript.Geometry.Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "80ab989f44dd404daaba02311e809cb8",
          "Name": "scale_factor",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a79187bb4fb7494eb6189b6e68287c74",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Scale Vector uniformly around the origin\n\nVector.Scale (scale_factor: double = 1): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.X",
      "Id": "46bf60c3e6cb49d89f41e1e0323ef2de",
      "Inputs": [
        {
          "Id": "677e9ea9220c4f9f9644cea4e22a5341",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "025aa597d67947579b8845e7f6131227",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the X component of a Point\n\nPoint.X: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Y",
      "Id": "3174f4f93b284f6c9c633e68f12466b8",
      "Inputs": [
        {
          "Id": "8d3e5836256c4776b0a44d4a834a48cc",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ff5a575792154451ad0103bafb7f72b6",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the Y component of a Point\n\nPoint.Y: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.X",
      "Id": "bcc66a5309aa4f80b39ad301dedc66df",
      "Inputs": [
        {
          "Id": "99fd88fd0ff741fe886f7ed08367b127",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b7fdce266c0342028e30996caae3aa5c",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the X component of a Point\n\nPoint.X: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Y",
      "Id": "587d26d6a1be438eaba1c0fc72f1f163",
      "Inputs": [
        {
          "Id": "611e0982546e46ba9c3108877cdffba6",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2ca969ea2d7d4307a6cf7d0279369726",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the Y component of a Point\n\nPoint.Y: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.Cross@Autodesk.DesignScript.Geometry.Vector",
      "Id": "fa45645c3d3246069dc7d2d5eef6d04b",
      "Inputs": [
        {
          "Id": "4fa0299ef30f46e0be0d06700afe6b9d",
          "Name": "vector",
          "Description": "Autodesk.DesignScript.Geometry.Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bd9b6e44c6944114ada51d57f1b947d4",
          "Name": "cross",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "8938fd383fea45d2a5df328a9dd4ae9a",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form the cross product of two vectors\n\nVector.Cross (cross: Vector): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.ZAxis",
      "Id": "f86831f20ae34770abd1e6c903cf3986",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "d91d30dc044e45fe99b9a27ed969d45c",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the canonical Z axis Vector (0,0,1)\n\nVector.ZAxis ( ): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.ByTwoPoints@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "886a7915a7a54fe0a13e77fe552c5570",
      "Inputs": [
        {
          "Id": "0d8f2016a22e4be0a1b4e5983567deaf",
          "Name": "start",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fb2d548247ef4888bbfccc65858d44ad",
          "Name": "end",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "cef83fa4fc65483fa5ac40738635bf05",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Vector by two end points. The result is a vector from the start to the end point.\n\nVector.ByTwoPoints (start: Point, end: Point): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.Normalized",
      "Id": "274212475d3244d285d84a5ae57d3ce7",
      "Inputs": [
        {
          "Id": "ff030384277a4fb1999835dfddb5fcdc",
          "Name": "vector",
          "Description": "Autodesk.DesignScript.Geometry.Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "fc6e7a98aeee4be1b7bca64e5d1081bc",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the normalized version of a vector\n\nVector.Normalized ( ): Vector"
    }
  ],
  "Connectors": [
    {
      "Start": "da5f88b84fb7484aa2b9c3350bd84dec",
      "End": "e425a32431f549b48e470bbae00a58b5",
      "Id": "c3fd8d850ae045c9ad872354dc4aa433"
    },
    {
      "Start": "994ce356fd584a00a78e81740d8b4b20",
      "End": "677e9ea9220c4f9f9644cea4e22a5341",
      "Id": "397ae6bbb5b44a1cb95aa20c0e4bdcda"
    },
    {
      "Start": "994ce356fd584a00a78e81740d8b4b20",
      "End": "8d3e5836256c4776b0a44d4a834a48cc",
      "Id": "d990c7e222104e8980628327fff056de"
    },
    {
      "Start": "a08059741c894714be0e04cc155bf195",
      "End": "99fd88fd0ff741fe886f7ed08367b127",
      "Id": "2a6b2aebb27f4fc9a1268998e84da488"
    },
    {
      "Start": "a08059741c894714be0e04cc155bf195",
      "End": "611e0982546e46ba9c3108877cdffba6",
      "Id": "c508c2709f9f4f749ff655ffff197199"
    },
    {
      "Start": "796a7561485c4491a6bc66038209bf9d",
      "End": "81cc2b89eaa34c02958697eee31f5f70",
      "Id": "41141841e86d4303917445d96e08d2bf"
    },
    {
      "Start": "b4b59b557ffa4b75998eb7e76d75abf6",
      "End": "8f743ce6223f4be3b4fdf76e12de4199",
      "Id": "fa7761e202a44b11ab2ce69eb419effd"
    },
    {
      "Start": "88efafa634af4dac9e63d92168a42f9e",
      "End": "6ee4a10f2a7f4f7bb732de96538f37db",
      "Id": "cfb2365b091648edbe680885158ac657"
    },
    {
      "Start": "b9b09d71bfdf44c8894134eb7185c451",
      "End": "2e12008398d94c4da2e2da21b2d9b053",
      "Id": "3ad6ead140724338bb4aaaf9f52fb447"
    },
    {
      "Start": "b9b09d71bfdf44c8894134eb7185c451",
      "End": "9499db4003b24bc1bc43e91feb33916a",
      "Id": "e297429cef8d4bfbb3c9952f9116d750"
    },
    {
      "Start": "f14aac46ba7a47b5abc4bca97f815f8a",
      "End": "a05476966f5947bdb2db92cf99e4d66e",
      "Id": "d9877761b63445b4bd3e0a8b22a10257"
    },
    {
      "Start": "f14aac46ba7a47b5abc4bca97f815f8a",
      "End": "b4a5b036aeee4efaa58b608ecf633b6b",
      "Id": "dd4db2fb219d4201b07a068013dacd00"
    },
    {
      "Start": "d1c009bc73cd4333a2273aff52ed7690",
      "End": "1cf65e23a1384ba7ba2c93d7c924e495",
      "Id": "4af8335487f840f78037402c18608b01"
    },
    {
      "Start": "4ccd9510d178430a91f188bd478e7204",
      "End": "2fed2d491ad84690bc43fcf01f87cff3",
      "Id": "fee36d606f5849a8b49cc4b7b83ff4a4"
    },
    {
      "Start": "4ccd9510d178430a91f188bd478e7204",
      "End": "2e351439cb134763a35b3e36bab70cf8",
      "Id": "61d77ff220584a9aa86e0e2fe15f0196"
    },
    {
      "Start": "2431103755aa4cb190d4fb5c8c8369e4",
      "End": "79419061dbee465abbcbab87091f40c3",
      "Id": "fd9fc09366fd4e33b3c20d87fe4a9f21"
    },
    {
      "Start": "da116087475a4d2a85411987a409c4de",
      "End": "80ab989f44dd404daaba02311e809cb8",
      "Id": "7668f9e8701541dfb7d26212da3f19e6"
    },
    {
      "Start": "6cfbb1a0796f41828e5dfa9da095764e",
      "End": "c1adcc4fc5cb4efda1aa6f0feb30cf07",
      "Id": "207caee720e34f96a7be41ca14616a63"
    },
    {
      "Start": "811c24f285484a9cbcaca83ae83df8c8",
      "End": "fb0311bf0bd14e979254ba8cafce2122",
      "Id": "ebc6e3b4b5bd4dd28a6618d71e3dc2da"
    },
    {
      "Start": "5cb148dee9164042b5a78210ceb9838c",
      "End": "e65c36a1fc044b22a1958c3154d423c0",
      "Id": "5e6111fc22ee43cf99ba206d900f228c"
    },
    {
      "Start": "5cb148dee9164042b5a78210ceb9838c",
      "End": "fb2d548247ef4888bbfccc65858d44ad",
      "Id": "5d504230c5134c44a72ea32f03dbd76d"
    },
    {
      "Start": "4510204efec54f32a59deaf655de38b5",
      "End": "c172d2af8f534a1ea57ce187f0d21678",
      "Id": "b898c923f9ee4b78aba33189301e8945"
    },
    {
      "Start": "4510204efec54f32a59deaf655de38b5",
      "End": "0d8f2016a22e4be0a1b4e5983567deaf",
      "Id": "908edcc88c924218bf3f3abe92727b35"
    },
    {
      "Start": "2a31fa7c13a24667997be67ac2e6e731",
      "End": "cba0d3a62e29459b8b247e6ec3c955ac",
      "Id": "b95cbca1105d48f5b70c3bfdac4f5917"
    },
    {
      "Start": "a79187bb4fb7494eb6189b6e68287c74",
      "End": "43389496d54f4a36af60849d0073d09e",
      "Id": "f6974537f6a743c79d9a612cf345e623"
    },
    {
      "Start": "a79187bb4fb7494eb6189b6e68287c74",
      "End": "bb1d810873b04fc2b092a61dca337419",
      "Id": "19607e72f3e4457487ff4dd703a82180"
    },
    {
      "Start": "025aa597d67947579b8845e7f6131227",
      "End": "4a649f14fcfc4adb8dd89202fe335f3f",
      "Id": "e2f185e0e9b04f34a36263a137d27d09"
    },
    {
      "Start": "ff5a575792154451ad0103bafb7f72b6",
      "End": "901c9cdcfb1c47979c75e7812b35b4b6",
      "Id": "89bb7882d8a9437ea3eba05d504e01d0"
    },
    {
      "Start": "b7fdce266c0342028e30996caae3aa5c",
      "End": "e32e2a662c0b4cd0a4032fdb4df33fd7",
      "Id": "48ce6f4da96e4766b78f012bc9bc41dc"
    },
    {
      "Start": "2ca969ea2d7d4307a6cf7d0279369726",
      "End": "4fbfc89f75134c90b1a74c0a7b2024d3",
      "Id": "91c7d7fc28c24277835c953315de2110"
    },
    {
      "Start": "8938fd383fea45d2a5df328a9dd4ae9a",
      "End": "e0b2d3645bb444a992aa15ead74e88a3",
      "Id": "cc0ab8c9fcde4114befcc3e68855be0b"
    },
    {
      "Start": "d91d30dc044e45fe99b9a27ed969d45c",
      "End": "bd9b6e44c6944114ada51d57f1b947d4",
      "Id": "9fc13c5a5b6046eda0129e249ff1cf22"
    },
    {
      "Start": "cef83fa4fc65483fa5ac40738635bf05",
      "End": "ff030384277a4fb1999835dfddb5fcdc",
      "Id": "d4309d520d5141bdaee4eb16b3c2ceb7"
    },
    {
      "Start": "fc6e7a98aeee4be1b7bca64e5d1081bc",
      "End": "4fa0299ef30f46e0be0d06700afe6b9d",
      "Id": "2ab06c4e25fa43e3bb565496dc814e25"
    }
  ],
  "Dependencies": [
    "e29fe7ec-cf80-41fd-a1a1-d55b01e15697",
    "43df6cfe-4f8f-42e9-8996-43441bebd19d"
  ],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.0.4654",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "Id": "de4ee521d19f404690e2749c4add666e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2516.73420146273,
        "Y": 747.659473921598
      },
      {
        "Id": "1b41fe9ccefc4707a8e4dcdb3d8d226c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 244.464462622218,
        "Y": 769.081060390292
      },
      {
        "Id": "77724451d13545079ba7c5d636637a96",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 261.357734655702,
        "Y": 976.999770205692
      },
      {
        "Id": "953cdc3aa06b4f71a5d930a462134257",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 329.806631426539,
        "Y": 1127.80573943683
      },
      {
        "Id": "02de61aab9a14c1dbe46e10e9bc97000",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 3204.63798044189,
        "Y": 783.054429472428
      },
      {
        "Id": "1a5794e0884d48cdba01d524fd46214d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2863.95579363812,
        "Y": 900.760634006694
      },
      {
        "Id": "0108fe09264c46a2aca8f4d5d82e2366",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Add Intersect To Divided Surface",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2860.63798044189,
        "Y": 783.054429472428
      },
      {
        "Id": "ad17e8bd13204dbaad00a6bac5352f99",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.Subtract",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2238.13039053537,
        "Y": 950.656631288819
      },
      {
        "Id": "efedc59ecafc42d48ac059826ab61510",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Curve.PointAtParameter",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1313.82569884669,
        "Y": 969.329453343135
      },
      {
        "Id": "a5b4099b6e72473b8b6dec4ae688379d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "ReferencePlane.ByStartPointEndPoint",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2543.11981742253,
        "Y": 872.853206062499
      },
      {
        "Id": "a6a7a211e68e4d378eafc78cc82e44d4",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "List.DropLastItem",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1130.20961531258,
        "Y": 1124.93630379577
      },
      {
        "Id": "3a33a6aa6205440d9cd349ec9dfedc72",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Line.ByStartPointEndPoint",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1035.28943653647,
        "Y": 841.731835971972
      },
      {
        "Id": "6c8eac660c2a4f7c868ea725cf4c6213",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "List.RestOfItems",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 927.920709724151,
        "Y": 1124.93630379577
      },
      {
        "Id": "27f3d287d90a4e1e890646e6304f8703",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1794.26842282271,
        "Y": 838.717823436201
      },
      {
        "Id": "f5ff068bed22459896c6b73915ccea61",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.Add",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2250.57893857158,
        "Y": 812.166534385971
      },
      {
        "Id": "d391df1c98514715a1358a87db5dfc47",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Curve.Length",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1541.01170050755,
        "Y": 835.507561953866
      },
      {
        "Id": "a24282a204f246a99fcbd24ba49b34c7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.ByCoordinates",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 824.272310404881,
        "Y": 953.539877739028
      },
      {
        "Id": "f4d9b10ae9da44f0b561e4e37ea32894",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.ByCoordinates",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 809.65950338015,
        "Y": 745.255588691336
      },
      {
        "Id": "8c8cf82eb2a545b59142f79bc5d0f9cf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 589.478847218611,
        "Y": 1130.61953604936
      },
      {
        "Id": "2a8db5d0e91f47b09e8fe95ca9d70444",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Vector.Scale",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1950.25771719798,
        "Y": 732.807040655125
      },
      {
        "Id": "46bf60c3e6cb49d89f41e1e0323ef2de",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.X",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 566.912816674031,
        "Y": 715.690287105335
      },
      {
        "Id": "3174f4f93b284f6c9c633e68f12466b8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.Y",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 571.581022187611,
        "Y": 812.166534385971
      },
      {
        "Id": "bcc66a5309aa4f80b39ad301dedc66df",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.X",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 581.525623698761,
        "Y": 923.974576153027
      },
      {
        "Id": "587d26d6a1be438eaba1c0fc72f1f163",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.Y",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 586.19382921234,
        "Y": 1020.45082343366
      },
      {
        "Id": "fa45645c3d3246069dc7d2d5eef6d04b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Vector.Cross",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1696.61855096018,
        "Y": 673.676437483123
      },
      {
        "Id": "f86831f20ae34770abd1e6c903cf3986",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Vector.ZAxis",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1539.45563200302,
        "Y": 745.255588691336
      },
      {
        "Id": "886a7915a7a54fe0a13e77fe552c5570",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Vector.ByTwoPoints",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1184.672012971,
        "Y": 655.003615428806
      },
      {
        "Id": "274212475d3244d285d84a5ae57d3ce7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Vector.Normalized",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1435.19904219975,
        "Y": 653.44754692428
      }
    ],
    "Annotations": [
      {
        "Id": "6abf71ff68e44d498eb0ae7afa766081",
        "Title": "Create points for subdivisions",
        "Nodes": [],
        "Left": 1319.84416500964,
        "Top": 930.999967127083,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "2df5e1765c964fb688e77080632d4413",
        "Title": "Create a set of orthogonal planes to curve 1",
        "Nodes": [],
        "Left": 2542.91400956738,
        "Top": 826.743377323815,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "8ea3312034dd466aa9d60756df99e6db",
        "Title": "Project the points to the XY plane and create a line between them",
        "Nodes": [],
        "Left": 1030.41542316774,
        "Top": 784.729527701603,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "0c392a93f39f4926ac183b3556d35bae",
        "Title": "Find vector orthogonal to line",
        "Nodes": [],
        "Left": 1973.39293691072,
        "Top": 685.141143411915,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      }
    ],
    "X": -56.2362704247676,
    "Y": 15.7814471837413,
    "Zoom": 0.615937071974734
  }
}