{
  "Uuid": "43aab40b-2645-4c59-b2e8-bf17b48b5fb9",
  "IsCustomNode": true,
  "Category": "Clockwork.Revit.Elements.Actions",
  "Description": "Transform a slab shape based on a list of Points",
  "Name": "Floor.SlabShapeByPoints",
  "ElementResolver": {
    "ResolutionMap": {
      "Floor": {
        "Key": "Revit.Elements.Floor",
        "Value": "RevitNodes.dll"
      },
      "Autodesk.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "points",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": -1,
        "DefaultValue": null
      },
      "Id": "5bb0ff9a241549dcba603dcc5445ee1c",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "542fc56af8274858b46d571885d1fa1c",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "floor",
        "TypeName": "var",
        "TypeRank": -1,
        "DefaultValue": null
      },
      "Id": "ef4556c3fc584ae19feed7d62f9d2795",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "dc2bf57eddc840099974feb2e8a1c7ce",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "floor",
      "Id": "e34a3b6a64974e21b5f4d6ace55f2c7b",
      "Inputs": [
        {
          "Id": "12e598e5f59c4e5c8be3caf6c8af772c",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "d145e1db-d069-452f-b46d-7ad9b0fd906d",
      "FunctionType": "Graph",
      "NodeType": "FunctionNode",
      "Id": "918e92e658814f86a959f72c3eb96d06",
      "Inputs": [
        {
          "Id": "b2cd7e8966df433ea08ef67019117932",
          "Name": "points",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d835513ac07449368443b3307d56bbc4",
          "Name": "roof",
          "Description": "Input #2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2e0befa98d9b4d679119b0dfce5984ff",
          "Name": "roof",
          "Description": "Output #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1e4bc43b74a94de9bea69aaf79d558cf",
          "Name": "success",
          "Description": "Output #2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Transform a slab shape based on a list of Points."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "success",
      "Id": "a91fe14c4fe14b47b1bdb11494b3e13c",
      "Inputs": [
        {
          "Id": "ab5986758fe64763b6207417e811e090",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    }
  ],
  "Connectors": [
    {
      "Start": "542fc56af8274858b46d571885d1fa1c",
      "End": "b2cd7e8966df433ea08ef67019117932",
      "Id": "556016975ee6411e8414577ff14305c2"
    },
    {
      "Start": "dc2bf57eddc840099974feb2e8a1c7ce",
      "End": "d835513ac07449368443b3307d56bbc4",
      "Id": "3a8e4479e3fc42d1b80acbb434bf139d"
    },
    {
      "Start": "2e0befa98d9b4d679119b0dfce5984ff",
      "End": "12e598e5f59c4e5c8be3caf6c8af772c",
      "Id": "9e039ce7eef949aea78a8416c64953a6"
    },
    {
      "Start": "1e4bc43b74a94de9bea69aaf79d558cf",
      "End": "ab5986758fe64763b6207417e811e090",
      "Id": "10cb31988ee2422d9f1bc66e572397d5"
    }
  ],
  "Dependencies": [
    "d145e1db-d069-452f-b46d-7ad9b0fd906d"
  ],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.0.4654",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "Id": "5bb0ff9a241549dcba603dcc5445ee1c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 0.0,
        "Y": 0.0
      },
      {
        "Id": "ef4556c3fc584ae19feed7d62f9d2795",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 0.0,
        "Y": 84.0
      },
      {
        "Id": "e34a3b6a64974e21b5f4d6ace55f2c7b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 602.820638820639,
        "Y": 29.0
      },
      {
        "Id": "918e92e658814f86a959f72c3eb96d06",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Roof.SlabShapeByPoints",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 340.0,
        "Y": 29.0
      },
      {
        "Id": "a91fe14c4fe14b47b1bdb11494b3e13c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 599.447174447175,
        "Y": 101.520884520884
      }
    ],
    "Annotations": [],
    "X": 30.0000000000001,
    "Y": 287.028443113772,
    "Zoom": 1.2185628742515
  }
}