{
  "Uuid": "cbe6db5e-3248-46ff-87e4-b620a1abf252",
  "IsCustomNode": true,
  "Category": "Clockwork.Revit.Elements.Query",
  "Description": "Retrieves the plane of a given level",
  "Name": "Level.Plane",
  "ElementResolver": {
    "ResolutionMap": {
      "Plane": {
        "Key": "Autodesk.DesignScript.Geometry.Plane",
        "Value": "ProtoGeometry.dll"
      },
      "Vector": {
        "Key": "Autodesk.DesignScript.Geometry.Vector",
        "Value": "ProtoGeometry.dll"
      },
      "Level": {
        "Key": "Revit.Elements.Level",
        "Value": "RevitNodes.dll"
      },
      "Autodesk.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "Autodesk.DesignScript.Geometry.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "level",
        "TypeName": "Revit.Elements.Level",
        "TypeRank": 0,
        "DefaultValue": null
      },
      "Id": "ff8b00114e42418aac2acccba899afd2",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "3cf48faa775641a89caa414f1c82ab7c",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "plane",
      "Id": "d4504d40484944e78ba43a1a2e5f2fcb",
      "Inputs": [
        {
          "Id": "9c3e56522a1c485e948020538a7f17a5",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "5e617742aff842fb816d58ce2183561d",
      "Inputs": [
        {
          "Id": "7a2aedad49ac4180a4928a40230c1c2e",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bcc6cb813b9f44469d78a433ecc3ff0c",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "cc84d98cef0d4cb9b771644d13c30b50",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3402a612129f45c186c940ec2f3fcf6a",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "0;",
      "Id": "2ef0b539a7324b43921be0b48cb3a9b7",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "17bb40ce95854a12b024a0d240a4c2ea",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Level.Elevation",
      "Id": "2470a7c1192a4091bb82926527f1237b",
      "Inputs": [
        {
          "Id": "8bfc2acc908344928ad545cfcfd045f9",
          "Name": "level",
          "Description": "Revit.Elements.Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "622056d9cbe4437d95891c4538067311",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The elevation of the level above ground level\n\nLevel.Elevation: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Plane.ByOriginNormal@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector",
      "Id": "c03cee6d60814b3683c98651619b3df2",
      "Inputs": [
        {
          "Id": "574cea2d89454da39c13648972bef8fb",
          "Name": "origin",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4bb1b229b0a54b469c655f1b8fd0249f",
          "Name": "normal",
          "Description": "Vector\nDefault value : Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "195840dca81d46d6bdb5c2b3634f5df8",
          "Name": "Plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Plane centered at root Point, with input normal Vector.\n\nPlane.ByOriginNormal (origin: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), normal: Vector = Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1)): Plane"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.ZAxis",
      "Id": "3f90f293862248789bcdaa0f9e5d7a86",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "5b4375bb220a4521b1d153b9a0a638ef",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the canonical Z axis Vector (0,0,1)\n\nVector.ZAxis ( ): Vector"
    }
  ],
  "Connectors": [
    {
      "Start": "3cf48faa775641a89caa414f1c82ab7c",
      "End": "8bfc2acc908344928ad545cfcfd045f9",
      "Id": "8f2ca3f509b049188fe082088b3a38eb"
    },
    {
      "Start": "3402a612129f45c186c940ec2f3fcf6a",
      "End": "574cea2d89454da39c13648972bef8fb",
      "Id": "7b8487b8f3f1424c9d6d20de749b3f31"
    },
    {
      "Start": "17bb40ce95854a12b024a0d240a4c2ea",
      "End": "7a2aedad49ac4180a4928a40230c1c2e",
      "Id": "3f87e93f72d245ac8b0ed12a0436d319"
    },
    {
      "Start": "17bb40ce95854a12b024a0d240a4c2ea",
      "End": "bcc6cb813b9f44469d78a433ecc3ff0c",
      "Id": "1f4cec37edac46ef9e3f69bf95aa02e7"
    },
    {
      "Start": "622056d9cbe4437d95891c4538067311",
      "End": "cc84d98cef0d4cb9b771644d13c30b50",
      "Id": "bde13e0782c445efbf9d96431d9e2189"
    },
    {
      "Start": "195840dca81d46d6bdb5c2b3634f5df8",
      "End": "9c3e56522a1c485e948020538a7f17a5",
      "Id": "bec07049862c44f79b94baf65ab69965"
    },
    {
      "Start": "5b4375bb220a4521b1d153b9a0a638ef",
      "End": "4bb1b229b0a54b469c655f1b8fd0249f",
      "Id": "1db187ed18624c57bed8476300328dc4"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.0.4654",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "Id": "ff8b00114e42418aac2acccba899afd2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -58.7926592255341,
        "Y": -95.8486825308794
      },
      {
        "Id": "d4504d40484944e78ba43a1a2e5f2fcb",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1022.20734077447,
        "Y": -105.848682530879
      },
      {
        "Id": "5e617742aff842fb816d58ce2183561d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.ByCoordinates",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 467.207340774466,
        "Y": -172.848682530879
      },
      {
        "Id": "2ef0b539a7324b43921be0b48cb3a9b7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 178.207340774466,
        "Y": -180.635349197546
      },
      {
        "Id": "2470a7c1192a4091bb82926527f1237b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Level.Elevation",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 178.207340774466,
        "Y": -95.8486825308794
      },
      {
        "Id": "c03cee6d60814b3683c98651619b3df2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Plane.ByOriginNormal",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 725.207340774466,
        "Y": -105.848682530879
      },
      {
        "Id": "3f90f293862248789bcdaa0f9e5d7a86",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Vector.ZAxis",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 467.207340774466,
        "Y": -12.8486825308794
      }
    ],
    "Annotations": [],
    "X": 127.991018531612,
    "Y": 366.205676676535,
    "Zoom": 1.39741847850902
  }
}