{
  "Uuid": "07195267-53da-4fa3-8410-62807cdbab46",
  "IsCustomNode": true,
  "Category": "Clockwork.Revit.Views.Query",
  "Description": "Returns the direction of a view",
  "Name": "View.Direction",
  "ElementResolver": {
    "ResolutionMap": {
      "Plane": {
        "Key": "Autodesk.DesignScript.Geometry.Plane",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "view",
        "TypeName": "var",
        "TypeRank": -1,
        "DefaultValue": null
      },
      "Id": "788d7d58fa3c4d898bba7725473064ab",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "73e262b57bae4a319cf4ddfe35d35d69",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "vector",
      "Id": "8fb30b938ee548158a6ee62632447bdf",
      "Inputs": [
        {
          "Id": "2ef4ac9b30c341b9a4dd661e08f4f46d",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\n\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\ndef ViewDirection(view):\r\n\tif hasattr(view, \"ViewDirection\"):\r\n\t\treturn view.ViewDirection.ToVector()\r\n\telse: return None\r\n\r\nviews = UnwrapElement(IN[0])\r\n\r\nif isinstance(IN[0], list): OUT = [ViewDirection(x) for x in views]\r\nelse: OUT = ViewDirection(views)",
      "VariableInputPorts": true,
      "Id": "542a73da013c4c5f8e340ed4e523fb2c",
      "Inputs": [
        {
          "Id": "c58190e34871445fa0aa0af28d66fc5a",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "95b2d44415854791aaedea77b9b81034",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    }
  ],
  "Connectors": [
    {
      "Start": "73e262b57bae4a319cf4ddfe35d35d69",
      "End": "c58190e34871445fa0aa0af28d66fc5a",
      "Id": "ad90125d10db45af912fb82fdffc967e"
    },
    {
      "Start": "95b2d44415854791aaedea77b9b81034",
      "End": "2ef4ac9b30c341b9a4dd661e08f4f46d",
      "Id": "c18f75fabfba44c28c2f0fb9d434a470"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.0.4654",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "Id": "788d7d58fa3c4d898bba7725473064ab",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 360.990694185428,
        "Y": 233.31641327983
      },
      {
        "Id": "8fb30b938ee548158a6ee62632447bdf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 747.990694185428,
        "Y": 233.31641327983
      },
      {
        "Id": "542a73da013c4c5f8e340ed4e523fb2c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Python Script",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 523.990694185428,
        "Y": 233.31641327983
      }
    ],
    "Annotations": [],
    "X": 100.0,
    "Y": 176.0,
    "Zoom": 1.0
  }
}