<Workspace Version="1.3.3.4651" X="-330.604124784251" Y="-344.686764524973" zoom="1.16438980805626" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="FloorPlanView" resolvedName="Revit.Elements.Views.FloorPlanView" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="cbda92a2-1994-441e-9d63-6bb043306489" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="SpotCoordinate.ByPoint" x="634.374051680547" y="495.566954643628" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="True" />
      <ID value="afb4fce4-6495-411d-839b-5f3808382495" />
      <Name value="SpotCoordinate.ByPoint" />
      <Description value="Places a spot coordinate at a given point in a given view. May not work in all view types." />
      <Inputs>
        <Input value="point" />
        <Input value="view" />
        <Input value="bend" />
        <Input value="end" />
        <Input value="hasLeader" />
      </Inputs>
      <Outputs>
        <Output value="spotCoordinate" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9f431e6e-da50-4101-859f-4bbd1bf61422" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.Origin" x="387.374051680547" y="417.566954643628" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.Origin" />
    <DSRevitNodesUI.Views guid="e2a7ee5c-26b3-4b29-aebb-9eb719538001" type="DSRevitNodesUI.Views" nickname="Views" x="387.374051680547" y="525.566954643628" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="9:Ebene 0" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="37dc3ffa-84d9-4dc5-ace6-2763b87e72b3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.XAxis" x="387.374051680547" y="634.566954643628" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.XAxis" />
    <CoreNodeModels.Watch guid="0dec25b6-91a9-4968-ba09-978c9a701de5" type="CoreNodeModels.Watch" nickname="Watch" x="998.374051680547" y="495.566954643628" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="cbda92a2-1994-441e-9d63-6bb043306489" start_index="0" end="0dec25b6-91a9-4968-ba09-978c9a701de5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9f431e6e-da50-4101-859f-4bbd1bf61422" start_index="0" end="cbda92a2-1994-441e-9d63-6bb043306489" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e2a7ee5c-26b3-4b29-aebb-9eb719538001" start_index="0" end="cbda92a2-1994-441e-9d63-6bb043306489" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="37dc3ffa-84d9-4dc5-ace6-2763b87e72b3" start_index="0" end="cbda92a2-1994-441e-9d63-6bb043306489" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="37dc3ffa-84d9-4dc5-ace6-2763b87e72b3" start_index="0" end="cbda92a2-1994-441e-9d63-6bb043306489" end_index="2" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="3ad50d05-2643-417f-b2df-f394f864d106" text="Run this graph on the CreateStuff_Sample.rvt file" x="683.349020127281" y="428.179009016258" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>