<Workspace Version="1.0.0.1180" X="24.9804150173894" Y="289.052599934719" zoom="0.998868722908503" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <DSRevitNodesUI.Views guid="14f21254-abe4-47e3-852d-68df333f93e3" type="DSRevitNodesUI.Views" nickname="Views" x="538.130135939541" y="107.340862644057" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="18:Ebene 0" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="fa99068a-67ed-4c9a-95af-441bed6081f2" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="5.02526995538972" y="18.844762332711" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="5;" ShouldFocus="false" />
    <CoreNodeModels.Watch guid="3f16b264-be62-4962-bcd6-1b2cda19cbef" type="CoreNodeModels.Watch" nickname="Watch" x="1073.4772097329" y="40.6603471187693" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9a29a1f5-3dc3-4e45-8cdd-b4faab6e3477" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Rectangle.ByWidthLength" x="219.256582730315" y="2.54235156635829" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength@double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="303cb93e-8c0a-4e77-9838-10d7328204a2" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Explode" x="494.602916583669" y="1.48462925746597" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Explode" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="38e573c5-b1c7-4538-abf7-f66097586dd8" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="DetailLine.FromCurve" x="805.771237133477" y="40.3371165726591" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <ID value="24214d3e-6159-4b2c-97b4-0a35a13518d9" />
      <Name value="DetailCurve.FromCurve" />
      <Description value="Creates a detail line based on a given curve" />
      <Inputs>
        <Input value="curve" />
        <Input value="view" />
      </Inputs>
      <Outputs>
        <Output value="detailLine" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="14f21254-abe4-47e3-852d-68df333f93e3" start_index="0" end="38e573c5-b1c7-4538-abf7-f66097586dd8" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fa99068a-67ed-4c9a-95af-441bed6081f2" start_index="0" end="9a29a1f5-3dc3-4e45-8cdd-b4faab6e3477" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fa99068a-67ed-4c9a-95af-441bed6081f2" start_index="0" end="9a29a1f5-3dc3-4e45-8cdd-b4faab6e3477" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9a29a1f5-3dc3-4e45-8cdd-b4faab6e3477" start_index="0" end="303cb93e-8c0a-4e77-9838-10d7328204a2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="303cb93e-8c0a-4e77-9838-10d7328204a2" start_index="0" end="38e573c5-b1c7-4538-abf7-f66097586dd8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="38e573c5-b1c7-4538-abf7-f66097586dd8" start_index="0" end="3f16b264-be62-4962-bcd6-1b2cda19cbef" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="4dde36dd-6f57-4b8b-ba58-a1e5aae4bef4" text="Run this file on the DetailComponent_Sample model in the extra folder." x="19.5983199675966" y="-74.0798409071041" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>