<Workspace Version="0.7.2.3911" X="261.055407663951" Y="192.409273443814" zoom="1.05192187360075" Description="Duplicates a given view. Duplication options: 0 = Duplicate, 1 = Duplicate with Detailing, 2 = Duplicate as Dependent View. Probably needs to be used in conjunction with a Transaction node." Category="CAAD_RWTH.Revit.Views.View.Actions" Name="View.Duplicate" ID="237e943c-c1a0-4936-9269-1b5ad1dc8b4c">
  <Elements>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="9946b309-ce58-49ea-b1d5-4e617bef849b" nickname="Turn Into List" x="242" y="29" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="Turn Into List" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="item" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="426563f5-9c8e-4016-8c0c-a9f1debb81fb" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="View(s)" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="c6ad3ceb-20c6-4892-be23-446170905627" nickname="Output" x="671" y="29" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="view(s)" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="284a20de-c0d8-4bed-ac89-965b5556d3fc" nickname="Input" x="0" y="84" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="duplication option" />
    </Dynamo.Nodes.Symbol>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="2d95b4f0-056e-446e-880c-cafdcc942c80" nickname="Python Script" x="447" y="29" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="2">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
views = UnwrapElement(IN[0])
option = IN[1]
elementlist = list()
if option == 1:
	dupopt = Autodesk.Revit.DB.ViewDuplicateOption.WithDetailing
elif option == 2:
	dupopt = Autodesk.Revit.DB.ViewDuplicateOption.AsDependent
else:
	dupopt = Autodesk.Revit.DB.ViewDuplicateOption.Duplicate

TransactionManager.Instance.EnsureInTransaction(doc)
for view in views:
	newview = view.Duplicate(dupopt)
	elementlist.append(doc.GetElement(newview))
TransactionManager.Instance.TransactionTaskDone()
	
OUT = elementlist</Script>
    </DSIronPythonNode.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="9946b309-ce58-49ea-b1d5-4e617bef849b" start_index="0" end="2d95b4f0-056e-446e-880c-cafdcc942c80" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="426563f5-9c8e-4016-8c0c-a9f1debb81fb" start_index="0" end="9946b309-ce58-49ea-b1d5-4e617bef849b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="284a20de-c0d8-4bed-ac89-965b5556d3fc" start_index="0" end="2d95b4f0-056e-446e-880c-cafdcc942c80" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="2d95b4f0-056e-446e-880c-cafdcc942c80" start_index="0" end="c6ad3ceb-20c6-4892-be23-446170905627" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>