<Workspace Version="0.8.3.2553" X="255" Y="298" zoom="1" Name="UnitType.FromDynamoUnitType" Description="Retrieves the corresponding Revit UnitType from a Dynamo UnitType" ID="90ad7237-1863-40d0-9a87-05b3be7624b3" Category="Clockwork.Revit.Elements.UnitType.Create">
  <NamespaceResolutionMap />
  <Elements>
    <DSIronPythonNode.PythonNode guid="978fef7f-2d39-4e4e-bc13-11ba66fbbe4f" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

dynunittype = IN[0]
if str(dynunittype) == 'DynamoUnits.Area':
	ut = UnitType.UT_Area
elif str(dynunittype) == 'DynamoUnits.Length':
	ut = UnitType.UT_Length
elif str(dynunittype) == 'DynamoUnits.Volume':
	ut = UnitType.UT_Volume
else:
	ut = null
OUT = ut</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Symbol guid="1b2d2fac-1cb0-4244-8cc5-d61f77b78658" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="DynamoUnitType" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="1695f946-c505-49f5-9db9-0f7282da27c3" type="Dynamo.Nodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="RevitUnitType" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="978fef7f-2d39-4e4e-bc13-11ba66fbbe4f" start_index="0" end="1695f946-c505-49f5-9db9-0f7282da27c3" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1b2d2fac-1cb0-4244-8cc5-d61f77b78658" start_index="0" end="978fef7f-2d39-4e4e-bc13-11ba66fbbe4f" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>